### ISSUE TITLE
Incomplete manualCapture request

### ISSUE THREAD

**Issue by baumwolli** [Adyen/adyen-commercetools#1065]
Hi,

i don't know if is a bug or miss configuration from our side. In our dev system looks the ``manualCapture`` request like this:
```json
{
    "method": "POST",
    "body": "{\"modificationAmount\":{\"value\":9995,\"currency\":\"EUR\"},\"originalReference\":\"C*********2\",\"reference\":\"L****************9\",\"metadata\":{\"ctProjectKey\":\"t**************l\"},\"merchantAccount\":\"B**************T\"}",
    "headers": {
        "Content-Type": "application/json",
        "X-Api-Key": "***"
    }
}
```
And everything is fine. But on production the request send:
```json
{
    "body": "{\"modificationAmount\":{\"value\":599,\"currency\":\"EUR\"},\"originalReference\":\"N***********2\",\"reference\":\"T**********8\",\"metadata\":{\"ctProjectKey\":\"t******s\"},\"merchantAccount\":\"B******E\"}"
}
```
And we get the response:
```json
{
    "name": "Error",
    "message": "Unable to receive non-JSON format resposne from Adyen API : 701 Method Payment not found in PaymentService",
    "stack": "Error: Unable to receive non-JSON format resposne from Adyen API : 701 Method Payment not found in PaymentService\n at fetchAsync (file:///app/src/service/web-component-service.js:232:13)\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (node:internal/process/task_queues:96:5)\n at async callAdyen (file:///app/src/service/web-component-service.js:186:35)\n at async Object.execute (file:///app/src/paymentHandler/manual-capture.handler.js:30:33)\n at async Promise.all (index 0)\n at async Object.handlePayment (file:///app/src/paymentHandler/payment-handler.js:51:28)\n at async processRequest (file:///app/src/api/payment/payment.controller.js:34:27)\n at async Server.<anonymous> (file:///app/src/server.js:15:9)"
}
```
I wondering that the method and header are missing. Because the buildRequest method always returns everything (https://github.com/commercetools/commercetools-adyen-integration/blob/v10.1.2/extension/src/service/web-component-service.js#L253)

I hope you have an idea where the error can be.
We have tried it with v10.1.2.
With version 9.7.0 it works. But we want to use the custom manual capture reference.

Best regards

baumwolli

**Comment by leungkinghin** [comment]
In v10.1.2, we have added an improvement to handle non-JSON response from Adyen. In the past, the error would still occur in response. But it would just be about JSON object parsing problem, not the actual error message from Adyen as same as now.

According to the 701 error code from the response, i guess there may have mistakes inside the given request.
https://docs.adyen.com/development-resources/error-codes#701-server-could-not-process-request

I would suggest you can raise a ticket in Adyen support and provide the involved request to them (including `originalReference` and `merchantAccount`), so that they can find out why 701 error code occurs and help us to understand what might go wrong.

If you want to use the custom manual capture reference, you can also try v10.1.1 which is the fix version.
https://github.com/commercetools/commercetools-adyen-integration/releases/tag/v10.1.1

**Comment by BielsasBucket** [comment]
Hi,

Check the legacyApiUrl you are using. After version 9.11 it was changed and we found it broke our ability to capture and refund.

For example, we had the following configured:

`"legacyApiBaseUrl": "https://pal-test.adyen.com/pal/servlet/Payment/v68"`

changing to:

`"legacyApiBaseUrl": "https://pal-test.adyen.com/pal/servlet"`

Or as you have in live solved the issue as [these changes](https://github.com/commercetools/commercetools-adyen-integration/pull/1004/files) altered the setting in the integration. See [extension/src/service/web-component-service.js](https://github.com/commercetools/commercetools-adyen-integration/pull/1004/files#diff-ead5b7b45e6b25a7b051c67f122adfd674c5a44bfbb2e1e75936f9c7ce2e83ca)

**Comment by leungkinghin** [comment]
@BielsasBucket In v9.11 we started to support the disabling of stored payment. Recurring API is involved which has different URL pattern as the Payment API. For this reason, we cannot assume anymore that `legacyApiBaseUrl` is requesting /Payment URI only. It can also be requesting `/Recurring` URI. Therefore we change the default value of `legacyApiBaseUrl`

Also, We suggest that you don't need to configure `legacyApiBaseUrl`, since your configured url is the same as the default value
https://github.com/commercetools/commercetools-adyen-integration/blob/master/extension/src/config/config.js#L101

Please free feel to let us know if you have concern.

**Comment by merijndebeer-adyen** [comment]
Dear reporter, we would like to notify you that the Adyen x CommerceTools integration has changed ownership. From July 1st 2023, Adyen has taken over support / maintenance tasks for this integration from CommerceTools. Thank you for your product feedback. We will take your suggestion into consideration and prioritize accordingly. If you are experiencing any ongoing issues with this integration please contact [Adyen Support](https://www.adyen.help/hc/en-us/requests/new) and we will make sure you will get the answers you need to get going.
