### ISSUE TITLE
TypeError in notification module.

### ISSUE THREAD

**Issue by ijn-kruso** [Adyen/adyen-commercetools#1107]
**Describe the bug**
Notification module throws error:
message":"Cannot read properties of undefined (reading 'version')","name":"TypeError","stack":"TypeError: Cannot read properties of undefined (reading 'version')\n at updatePaymentWithRepeater..."

**To Reproduce**
User creates a payment where transaction gets refused.
Notification module returns result with "success" : "false".
User tries again with correct details.
Adyen sends "success" : "true".
Notification module throws error:
message":"Cannot read properties of undefined (reading 'version')","name":"TypeError","stack":"TypeError: Cannot read properties of undefined (reading 'version')\n at updatePaymentWithRepeater..."
Notification module doesn't create a transaction on payment,

**Comment by DamjanLogeecom** [comment]
Hello @ijn-kruso, 

We noticed that you opened a new case regarding the issue you are facing with Adyen/CommerceTools integration.

Since you closed it, we wanted to ask if our assistance is still needed?

Thank you,

Kind regards

**Comment by ijn-kruso** [comment]
Hi @DamjanLogeecom 

The issue occurred when the user tried to pay the second time, without a new payment object being created. We solved it by adding additional checks, and made sure that in case of failure from notification, we create a new payment.

So I think the code works as it should, but could maybe be improved by another error message if a notification is received for an unknown PSP reference.

**Comment by jhilden** [comment]
We are seeing the same problem. We are running 10.1.2 of the notification module and it seems to be that this check is the culprit 
```
if (payment !== null)
```
https://github.com/Adyen/adyen-commercetools/blob/v10.1.2/notification/src/handler/notification/notification.handler.js#L57

It looks like it was was fixed by changing it to `if (payment)` in version 11.2.0.

Unfortunately upgrading to 11.x would be a major change for use right now :/ 

@DamjanLogeecom would you consider releasing a version 10.1.3 with that fix?
