### ISSUE TITLE
Inconsistent authorization state in commercetools

### ISSUE THREAD

**Issue by samriley** [Adyen/adyen-commercetools#1108]
Hi, we're experiencing some inconsistent statuses for authorization types when there is a failure to authorize, such as ```Refused (905_1 Could not find an acquirer account for the provided txvariant (uatp), currency (USD), and action (AUTH).)```. In Adyen the status shows as "Refused", however in commercetools the status is shown as "Pending". I've traced this to https://github.com/Adyen/adyen-commercetools/blame/292fc4492b81f0fe6a243ef8d5d1832bcb891051/notification/resources/adyen-events.json#L6 where it would appear that "Pending" is the status given to this type of notification (with "success": "false"). Given this was last changed 5 years ago when it was first written I wanted to get your thoughts before making the change.

**Comment by DamjanLogeecom** [comment]
Hello @samriley,

Thank you for reaching out to us regarding this issue.

We will review your inquiry and come back to you as soon as possible.

Kind regards

**Comment by DamjanLogeecom** [comment]
Hello samriley,

Please note that our team is still reviewing the Issue you have raised.

As soon as we have more information to provide, we will let you know promptly.

Kind regards.

**Comment by DamjanLogeecom** [comment]
Hello @samriley,

The state of the “Authorization” payment transaction in commercetools is set to “Pending” according to the expectations of the [commercetools payment transaction status](https://docs.commercetools.com/api/projects/payments#transactionstate).

Please note that commercetools expects “Failure” status to be set to a payment transaction when: “Transaction has unrecoverably failed“. Since it is possible for the customer to retry the payment after refusal, the “Authorization” payment transaction is kept in the “Pending” state but with a clear “Status” indicator. The “Authorization” payment transaction state will be updated to“Successful” if/when a new successful Adyen “AUTHORISATION” webhook is received.

If you have any further questions or concerns, please let us know.

Kind regards.

**Comment by samriley** [comment]
I could see that the payment state should be left as pending (although actually I dont think this extension sets the payment state), the transaction status however seems wrong. The commercetools docs say that pending is "The payment service has accepted the Transaction, but it is not completed yet.". If the notification webhook recieves ```"status":500,"errorCode":"905_1","message":"Could not find an acquirer account for the provided txvariant (uatp), currency (USD), and action (AUTH)."``` surely that transaction has complted and has "unrecoverably failed"? would it not be a new authorisation transaction that needs to be created at that point (assigned to the same payment)? or is it not possible to go from failed back to initial?

**Comment by DamjanLogeecom** [comment]
Hello @samriley 

We just wanted to let you know that our team is reviewing your last inquiry.

As soon as we have more information to provide, we will let you know.

Thank you,

Kind regards.

**Comment by DamjanLogeecom** [comment]
Hello @samriley,

Here is a quick update from our end.

Please note that your proposal is a change in the integration behavior and our team is currently evaluating the change.

We expect to provide you with a concrete update in the upcoming week.

Thank you,

Kind regards.

**Comment by DamjanLogeecom** [comment]
Hello @samriley,

Upon further review of your inquiry, we've determined that the behavior you observed is as expected. We will consider this for a future Change Request if more users report the same issue.

Thank you,

Kind regards,
