### ISSUE TITLE
Klarna and Ideal - No authorisation notification (v11.3.0)

### ISSUE THREAD

**Issue by MartinAKQA** [Adyen/adyen-commercetools#1130]
**Describe the bug**
Create a Klarna or Ideal payment based on an Adyen session 

**To Reproduce**
1. Create the payment
2. Open up the payment through impex
3. Verify there is no Authorisation notification, under interfaceInteractions

**Expected behavior**
I would expect the Klarna and Ideal payments to act like other types of payments, e.g. Vipps or credit card which gets an Authorisation notification pushed on the payment here under interfaceInteractions

**Screenshots**
![image](https://github.com/Adyen/adyen-commercetools/assets/84074754/bc921ff4-7a45-43a7-9105-50da1978d3d1)

**Additional context**
This is on a development setup.

**Comment by logeecom** [comment]
Hey @MartinAKQA 

Thank you for reaching out.

Please note that we could not reproduce this issue locally, but since interface interactions are inserted with the notification module, our suggestion is to inspect if [fallback in case metadata is not available](https://github.com/Adyen/adyen-commercetools/blob/master/notification/docs/IntegrationGuide.md#fallback-in-case-metadata-is-not-available) is setup. Maybe the notification module can’t find the commercetools payment entity from the webhook payload due to the missing project key from metadata.

Please check this and contact us if any further assistance is needed.

Best regards.

**Comment by logeecom** [comment]
Hey @MartinAKQA 

Could you please check in your Adyen Customer Area if webhooks for Klarna are failing? You can check the webhook response from the notification module under the “Developers > Event logs”.

Do you have any log messages from the notification module during the Klarna webhook processing?

Also, we can continue the communication through the mail in the thread 'Case 03436796: [Test Env] Commercetools - Adyen - notifcation no auth notification for klarna and ideal'

Best regards.
