### ISSUE TITLE
Add payment method name to payment objects

### ISSUE THREAD

**Issue by andihalberkamp** [Adyen/adyen-commercetools#1138]
Hi,

I have seen that the "payment method name" is not added to the payment object. Is this not done by purpose or can you add the name to the paymentobject, when it is created?
![Bildschirm­foto 2024-01-19 um 17 14 15](https://github.com/Adyen/adyen-commercetools/assets/120093696/96d420b4-cd25-466a-bcfd-a7246fa23f3d)

**Comment by logeecom** [comment]
Hey @andihalberkamp,

Thank you for reaching out.
Payment method names are set by the extension and notification modules based on the adyenPaymentMethodsToNames field in the [Environment variable configuration JSON](https://github.com/Adyen/adyen-commercetools/blob/master/extension/docs/HowToRun.md#environment-variable). Since commercetools “Payment method name” is a localized value, the adyenPaymentMethodsToNames field should contain each supported language's desired payment method name. If the Adyen extension/modification module does not find a configuration for the concrete payment method it will not set commercetools “Payment method name” field.

Best regards.
