### ISSUE TITLE
Notification handler overwrites valid/matching payment object key with PSP number

### ISSUE THREAD

**Issue by lwjoergf** [Adyen/adyen-commercetools#1144]
**Describe the bug**
notification module overwrites valid/matching payment object key with Adyen PSP number

**To Reproduce**
- The web application is creating a CT payment object with key 'XT000000000000344-PY1'.
- The web application is updating the CT payment object the field 'createSessionRequest'. the create session request has 'reference' set to value 'XT000000000000344-PY1'.
- complete the payment in Adyen web-drop-in
- notification module receives authorization success notification from Adyen. 
- the notification request contains the field 'merchantReference' with value 'XT000000000000344-PY1'.
- notification module updates payment object key with the Adyen PSP number, but it should not change the payment object key because the field 'merchantReference' matches the payment object key.
- /notification/src/handler/notification/notification.handler.js lines 221,222 do not consider the field 'notificationRequestItem.merchantReference'
- as result the condition on line 223 is false and the CT payment object key is overwritten

Suggested fixed:
const newPspReference = notificationRequestItem.merchantReference || notificationRequestItem.originalReference || pspReference

**Comment by logeecom** [comment]
Hey @lwjoergf 

Please note that the Adyen extension and notification modules use the payment key for internal logic to fetch and update CT payment instance. In general case, it is not possible to keep the custom payment key since Adyen modules support [custom refund reference](https://github.com/Adyen/adyen-commercetools/blob/master/extension/docs/Refund.md#custom-refund-reference). For more in-depth details regarding this decision please refer to [Matching Adyen Notification with commercetools payment](https://github.com/Adyen/adyen-commercetools/blob/master/docs/adr/0011-matching-adyen-notification.md) page.

Thank you,

Best regards.

**Comment by logeecom** [comment]
Hey @lwjoergf 

Do you still experience the same issue?

Best regards.
