### ISSUE TITLE
Paypal payment status is different in CT and Adyen

### ISSUE THREAD

**Issue by vasily-polonsky** [Adyen/adyen-commercetools#1178]
**Describe the bug**
We as using advanced integration flow https://github.com/Adyen/adyen-commercetools/blob/master/extension/docs/AdvancedCheckoutFlowIntegrationGuide.md . Adyen extension deployed as a lambda. We have an issue with paypal payment method. On submitAdditionalPaymentDetailsRequest we are getting “refused” result code. But according to Adyen, last status is Authorised.

**To Reproduce**
1 makePaymentRequest with paypal data from widget
2 submitAdditionalPaymentDetailsRequest with data from widget
3 See error in CT  submitAdditionalPaymentDetailsResponse
{
  merchantReference : "120000111_4eeb37d9-910f-442c-a8f6-d0514529332b_3ub"
  pspReference: "W8DBTZFHCTPRCK65"
  resultCode: "Refused"
}
4, Check result in adyen - ok

**Expected behavior**
Result should be in sync with adyen.

**Screenshots, logs, version**
extension / notification version - 11.5.1
[notification-logs.csv](https://github.com/user-attachments/files/15986062/notification-logs.csv)
[extension-logs.csv](https://github.com/user-attachments/files/15986063/extension-logs.csv)
Api calls from adyen-extension to adyen
```
{
  Timestamp: Jun 25, 2024, 14:06:27.000 GMT+2
  Request ID: KSDRJKKCWDVJPPT5
  Request: {
    "details": {
      "orderID": "EC-8E235261SN6222417",
      "payerID": "HLSTU5TH9NGPN",
      "paymentID": "8E235261SN6222417",
      "facilitatorAccessToken": "A21AAK9KIC4n6resaeNiu3FkOiEYj0cNto9f52FIv7RQQDG2sw39EGuv81ODrPXJ3HJbAuEDXFNjG5p765coJgPvXIWe2mkmQ",
      "paymentSource": "paypal"
    },
    "paymentData": "***...(1946)",
    "metadata": {
      "ctProjectKey": "*******************"
    },
    "merchantAccount": "MarcOPolo_ECOM_DE"
  }
  Response: {
    "additionalData": {
      "paypalEmail": "******************************"
    },
    "pspReference": "W8DBTZFHCTPRCK65",
    "resultCode": "Refused",
    "merchantReference": "120000111_4eeb37d9-910f-442c-a8f6-d0514529332b_3ub"
  }
}
```

```
{
  Timestamp: Jun 25, 2024, 14:06:25.000 GMT+2
  Request ID: RPMWFB3HNDL2DTT5
  Request: {
    "details": {
      "orderID": "EC-8E235261SN6222417",
      "payerID": "HLSTU5TH9NGPN",
      "paymentID": "8E235261SN6222417",
      "facilitatorAccessToken": "A21AAK9KIC4n6resaeNiu3FkOiEYj0cNto9f52FIv7RQQDG2sw39EGuv81ODrPXJ3HJbAuEDXFNjG5p765coJgPvXIWe2mkmQ",
      "paymentSource": "paypal"
    },
    "paymentData": "***...(1946)",
    "metadata": {
      "ctProjectKey": "*******************"
    },
    "merchantAccount": "MarcOPolo_ECOM_DE"
  }
  Response: {
    "additionalData": {
      "paypalEmail": "******************************"
    },
    "pspReference": "W8DBTZFHCTPRCK65",
    "resultCode": "Refused",
    "merchantReference": "120000111_4eeb37d9-910f-442c-a8f6-d0514529332b_3ub"
  }
}
```

```
{
  Timestamp: Jun 25, 2024, 14:06:23.000 GMT+2
  Request ID: BBNPDDTCC2LMSR65
  Request: {
    "details": {
      "orderID": "EC-8E235261SN6222417",
      "payerID": "HLSTU5TH9NGPN",
      "paymentID": "8E235261SN6222417",
      "facilitatorAccessToken": "A21AAK9KIC4n6resaeNiu3FkOiEYj0cNto9f52FIv7RQQDG2sw39EGuv81ODrPXJ3HJbAuEDXFNjG5p765coJgPvXIWe2mkmQ",
      "paymentSource": "paypal"
    },
    "paymentData": "***...(1946)",
    "metadata": {
      "ctProjectKey": "*******************"
    },
    "merchantAccount": "MarcOPolo_ECOM_DE"
  }
  Response: {
    "additionalData": {
      "paypalEmail": "******************************"
    },
    "pspReference": "W8DBTZFHCTPRCK65",
    "resultCode": "Authorised",
    "amount": {
      "currency": "EUR",
      "value": 9446
    },
    "merchantReference": "120000111_4eeb37d9-910f-442c-a8f6-d0514529332b_3ub",
    "paymentMethod": {
      "type": "paypal"
    }
  }
}
```

![Screenshot 2024-06-25 at 15 16 18](https://github.com/Adyen/adyen-commercetools/assets/6172199/9add6834-5bc2-40ce-bb98-b54b0158d550)
![Screenshot 2024-06-25 at 14 59 35](https://github.com/Adyen/adyen-commercetools/assets/6172199/dd843267-b92d-4ff7-ae6f-420c9e1aab15)

**Additional context**
Its also not clear why adyen-extension doing several requests to adyen

**Comment by adyen-integrations-support** [comment]
Hey @vasily-polonsky 

Our team is checking this matter and we will get back to you as soon as we have new valid information.

Thank you!

**Comment by adyen-integrations-support** [comment]
Hey @vasily-polonsky 


We have analyzed the logs and the images that you have provided. We think that the issue here is that the payment details request is sent three times in a row.

The Adyen extension module only handles changes in payment objects in CommerceTools.
In the module, during the payment process, the integration uses the payment object received from CommerceTools to check if the details request should be sent to Adyen. A new details request will be sent to Adyen only if the payment object in the custom fields does not contain “submit additional payment details response” and if the new details request is not the same as the one that has already been submitted (payment object contains this requests in its' interface interactions fields).

Since there are three details requests in your shop, this means that the payment object for this particular transaction has been updated in CommerceTools three times in a row, each time with different data.

We recommend you check your storefront implementation to prevent these consecutive changes from happening.

If the issue persists, we would need more detailed steps to try to reproduce the issue locally in order to further investigate it.

Best regards.

**Comment by vasily-polonsky** [comment]
Thanks for the answer
The missing field "timeoutInMs" in the extension setting in CT and the 3 retries setting for a CT client were the cause of this strange behaviour for paypal. After setting the timeout to 10 seconds the problem disappeared.
